# Generated by Django 5.2 on 2025-04-10 06:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_author_category_book_borrowrecord_recommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(
                default=django.utils.timezone.now,
                verbose_name='Date of Birth'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.CharField(
                default='Student',
                max_length=100,
                verbose_name='Major'
            ),
        ),
    ]
