# Generated by Django 5.2 on 2025-04-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_date_of_birth_user_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(
                choices=[
                    (0, 'Reader'),
                    (1, 'Librarian'),
                    (2, 'System Administrator'),
                ],
                default=0,
                max_length=100,
                verbose_name='User Type'
            ),
        ),
    ]
