# Generated by Django 5.2 on 2025-04-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='status',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('pending', 'Pending'),
                    ('borrowed', 'Borrowed'),
                    ('returned', 'Returned'),
                    ('rejected', 'Rejected'),
                    ('approval', 'Return Pending Approval'),
                ],
                default='pending',
                verbose_name='Status'
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(
                default='2025-01-11',
                verbose_name='Date of Birth'
            ),
        ),
    ]
