# Generated by Django 5.2 on 2025-04-19 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_borrowrecord_status_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Book Rating', 'verbose_name_plural': 'Book Ratings'},
        ),
        migrations.AddField(
            model_name='author',
            name='birth_date',
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name='Birth Date'
            ),
        ),
        migrations.AddField(
            model_name='author',
            name='country',
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name='Country'
            ),
        ),
        migrations.AddField(
            model_name='book',
            name='available_copies',
            field=models.IntegerField(
                default=1,
                verbose_name='Available Copies'
            ),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name='ISBN'
            ),
        ),
        migrations.AddField(
            model_name='book',
            name='publish_date',
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name='Publish Date'
            ),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name='Publisher'
            ),
        ),
        migrations.AddField(
            model_name='book',
            name='total_copies',
            field=models.IntegerField(
                default=1,
                verbose_name='Total Copies'
            ),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='actual_return_date',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='Actual Return Date'
            ),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='admin_remark',
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name='Admin Remark'
            ),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='subcategories',
                to='api.category',
                verbose_name='Parent Category'
            ),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recommended_reason',
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name='Recommended Reason'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name='Email'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name='Phone'
            ),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name='Cover Image'
            ),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='return_date',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='Expected Return Date'
            ),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='status',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('pending', 'Pending'),
                    ('borrowed', 'Borrowed'),
                    ('returned', 'Returned'),
                    ('rejected', 'Rejected'),
                    ('overdue', 'Overdue'),
                ],
                default='pending',
                verbose_name='Status'
            ),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.IntegerField(
                help_text='Range: 1–5',
                verbose_name='Score'
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name='Date of Birth'
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name='Major'
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(
                max_length=100,
                choices=[
                    (0, 'Reader'),
                    (1, 'Librarian'),
                    (2, 'System Administrator'),
                ],
                default=0,
                verbose_name='User Type'
            ),
        ),
    ]
