# Generated by Django 5.2 on 2025-04-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_rating_options_author_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='author',
            name='country',
        ),
        migrations.RemoveField(
            model_name='book',
            name='available_copies',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='book',
            name='total_copies',
        ),
        migrations.RemoveField(
            model_name='borrowrecord',
            name='actual_return_date',
        ),
        migrations.RemoveField(
            model_name='borrowrecord',
            name='admin_remark',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='recommended_reason',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='major',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='status',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('pending', 'Pending'),
                    ('borrowed', 'Borrowed'),
                    ('returned', 'Returned'),
                    ('rejected', 'Rejected'),
                ],
                default='pending',
                verbose_name='Status',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(
                max_length=100,
                choices=[
                    (0, 'Reader'),
                    (1, 'Librarian'),
                    (2, 'System Administrator'),
                ],
                default=0,
                verbose_name='User Type',
            ),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
